name: Update Docker Hub description

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'README.md'

jobs:
  update_description:
    name: Update description
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Update description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_NAMESPACE }}/${{ secrets.DOCKERHUB_IMAGENAME }}
          short-description: ${{ github.event.repository.description }}
          enable-url-completion: true